language: node_js
node_js:
  - 12

before_script:
  - npm install
  - npm run bootstrap
  - npm run build
  - docker-compose up -d security
  - docker-compose up -d scheduler
  - docker-compose up -d pdf

script:
  - npm run lint
  - npm run integration

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
  - git remote add pub https://github.com/TheSoftwareHouse/rad-modules-tools.git -f
  - git checkout master
  - npm install
  - npm run bootstrap
  - npm run build

deploy:
  provider: script
  script: npm run publish
  skip_cleanup: true
  on:
    tags: false
    branch: master
